FROM golang:1.24 AS builder

WORKDIR /app
COPY . .

RUN go build \
    -trimpath \
    -ldflags="-s -w -X github.com/cloudzero/cloudzero-insights-controller/pkg/build.Time=0 -X github.com/cloudzero/cloudzero-insights-controller/pkg/build.Rev=0.0.0-dev -X github.com/cloudzero/cloudzero-insights-controller/pkg/build.Tag=smoke-test" \
    -tags 'netgo osusergo' \
    -o /go/bin/shipper \
    ./cmd/cloudzero-shipper/main.go

FROM alpine:latest AS shipper
COPY --from=builder /go/bin/shipper /app/shipper
WORKDIR /app
ENTRYPOINT ["/app/shipper"]