FROM golang:1.24.2 AS builder

WORKDIR /app
COPY . .

RUN go build \
    -trimpath \
    -ldflags="-s -w -X github.com/cloudzero/cloudzero-insights-controller/app/build.Time=0 -X github.com/cloudzero/cloudzero-insights-controller/app/build.Rev=0.0.0-dev -X github.com/cloudzero/cloudzero-insights-controller/app/build.Tag=smoke-test" \
    -tags 'netgo osusergo' \
    -o /go/bin/remotewrite \
    ./mock/remotewrite/*.go

FROM alpine:latest AS remotewrite
COPY --from=builder /go/bin/remotewrite /app/remotewrite
WORKDIR /app
ENTRYPOINT ["/app/remotewrite"]
