FROM golang:1.24.1 AS builder

WORKDIR /app

# Download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY mock/remotewrite/ ./mock/remotewrite

# Build the app
RUN CGO_ENABLED=0 go build \
    -trimpath \
    -ldflags="-s -w" \
    -o /go/bin/remotewrite \
    ./mock/remotewrite/*.go

FROM alpine:latest AS remotewrite
COPY --from=builder /go/bin/remotewrite /app/remotewrite
WORKDIR /app
ENTRYPOINT ["/app/remotewrite"]
