FROM golang:1.24.1 AS builder

# Copy source code
COPY go.mod go.sum ./
COPY Makefile Makefile
COPY ./app ./app

# Build the app
RUN make /go/bin/cloudzero-shipper OUTPUT_BIN_DIR=/go/bin

FROM alpine:latest AS shipper
COPY --from=builder /go/bin/cloudzero-shipper /app/cloudzero-shipper
WORKDIR /app
ENTRYPOINT ["/app/cloudzero-shipper"]
