// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/types/errors.go
//
// Generated by this command:
//
//	mockgen -source=pkg/types/errors.go -destination=pkg/types/mocks/errors_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
