// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/types/resource.go
//
// Generated by this command:
//
//	mockgen -source=pkg/types/resource.go -destination=pkg/types/mocks/resource_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
