#!/bin/sh

echo "  prometheus, version 2.50.1 (branch: HEAD, revision: 8c9b0285360a0b6288d76214a75ce3025bce4050)"
echo "  build user:       root@6213bb3ee580"
echo "  build date:       20240226-11:38:47"
echo "  go version:       go1.21.7"
echo "  platform:         linux/arm64"
echo "  tags:             netgo,builtinassets,stringlabels"