name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * FRI'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.22
        env:
          LOG_LEVEL: debug
        with:
          docker-cmd-file: .github/renovate-entrypoint.sh
          docker-user: root
          configurationFile: .github/renovate-global-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
