name: k8s+k3s-version-test-matrix
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  k3s-version-test:
    name: k3s-test-${{ matrix.k8s_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version: [v1.26, v1.27, v1.28, v1.29, v1.30, v1.31, v1.32]
        # Some of these earlier versions don't appear to be available from the GH action (maybe a bug in the action...)
        # [v1.23, v1.24, v1.25, v1.26, v1.27, v1.28, v1.29, v1.30, v1.31, v1.32]

    steps:
      - uses: actions/checkout@v4
      - uses: alexellis/setup-arkade@v2
      - uses: alexellis/arkade-get@master
        with:
          kubectl: latest
          helm: latest
          k3d: latest
      - name: Create k3s ${{ matrix.k8s_version }} cluster
        uses: nolar/setup-k3d-k3s@v1.0.9
        id: k3s
        with:
          k3d-name: k3d-${{ matrix.k8s_version }}
          version: ${{ matrix.k8s_version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test nodes
        run: |
          echo "Waiting for nodes to be ready..."
          kubectl wait --for=condition=Ready nodes --all --timeout=5m
          kubectl get nodes -o wide

      - name: Install CZ Agent
        run: |
          echo "Applying CloudZero Agent Helm Chart"
          helm repo add prom https://prometheus-community.github.io/helm-charts
          helm dependency build ./helm
          export CLUSTERNAME="$(hostname)-$(date '+%Y%m%d%H%M%S')"
          echo $CLUSTERNAME
          make \
            CLOUDZERO_DEV_API_KEY="${{ secrets.CLOUDZERO_DEV_API_KEY }}" \
            CLUSTER_NAME="${CLUSTERNAME}" \
            helm-install

      - uses: kubeshop/setup-testkube@v1
        with:
          namespace: testkube
          version: 2.1.137
    
      - run: |
          testkube run testworkflow agent-basic-test -f ./tests/testkube/tests.yaml

      - name: Cleanup
        if: always()
        run: |
          k3d cluster rm k3d-${{ matrix.k8s_version }} || true
